on: [push]

name: example

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:

      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: "Activate Namespace"
        uses: okteto/namespace@latest
        with:
          name: cahox

      - name: "Deploy application"
        uses: okteto/apply@latest
        with:
          namespace: cahox
          manifest: k8s.yaml

      - name: "Push changes"
        uses: okteto/push@latest
        with:
          namespace: cahox
          name: hello-world