on: [push]

name: Main Workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          fetch-depth: 0
      - name: Build and SonarCloud Check
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar